services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: currency_converter_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.cache.json
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    restart: unless-stopped
    ipc: host # Recommended for Chromium in Docker

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: currency_converter_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: currency_network

